apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-registro-ponto-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-api-registro-ponto
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
