apiVersion: v1
kind: Service
metadata:
  name: fiap-registro-ponto-service
spec:
  selector:
    app: fiap-api-registro-ponto
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    #nodePort: 30000
  type: LoadBalancer
